from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.login, name='login'),
	url(r'^getselected_area$',views.getselected_area,name='getselected_area'),
	url(r'^login$',views.login, name='login'),
	url(r'^forgot_pass$',views.forgot_pass, name='forgot_pass'),
	url(r'^forgot_pass_chg/(?P<user>\w+)$',views.forgot_pass_chg, name='forgot_pass_chg'),
	url(r'^user_verify_email/(?P<user>\w+)$',views.user_verify_email, name='user_verify_email'),
	url(r'^regenerate_otp/(?P<user>\w+)$',views.regenerate_otp, name='regenerate_otp'),
	url(r'^otp_email_chg/(?P<user>\w+)$',views.otp_email_chg, name='otp_email_chg'),
	url(r'^dashboard/(?P<user>\w+)$',views.dashboard, name='dashboard'),
	url(r'^logout/(?P<user>\w+)$',views.logout, name='logout'),
	url(r'^register$',views.register, name='register'),
	url(r'^activity_log/(?P<user>\w+)$',views.activity_log,name='activity_log'),
	url(r'^profile/(?P<user>\w+)$',views.profile,name='profile'),
	url(r'^settings/(?P<user>\w+)$',views.settings,name='settings'),
	url(r'^chg_passwd/(?P<user>\w+)$',views.chg_passwd,name='chg_passwd'),
	url(r'^givefeed/(?P<user>\w+)$',views.givefeed,name='givefeed'),
	url(r'^showfeed/(?P<user>\w+)$',views.showfeed,name='showfeed'),
	url(r'^takepatient/(?P<user>\w+)$',views.takepatient,name='takepatient'),
	url(r'^takepatient_otp_user/(?P<user>\w+)$',views.takepatient_otp_user,name='takepatient_otp_user'),
	url(r'^enter_case/(?P<user>\w+)$',views.enter_case,name='enter_case'),
	url(r'^new_case_pageone/(?P<user>\w+)$',views.new_case_pageone,name='new_case_pageone'),
	url(r'^addsymptcatajax/(?P<user>\w+)$',views.addsymptcatajax,name='addsymptcatajax'),
	url(r'^addsymptajax/(?P<user>\w+)$',views.addsymptajax,name='addsymptajax'),
	url(r'^addinjajax/(?P<user>\w+)$',views.addinjajax,name='addinjajax'),
	url(r'^getsymptajax/(?P<user>\w+)$',views.getsymptajax,name='getsymptajax'),
	url(r'^getdisajax/(?P<user>\w+)$',views.getdisajax,name='getdisajax'),
	url(r'^adddiseasecatajax/(?P<user>\w+)$',views.adddiseasecatajax,name='adddiseasecatajax'),
	url(r'^adddiseaseajax/(?P<user>\w+)$',views.adddiseaseajax,name='adddiseaseajax'),
	url(r'^get_cons_doc/(?P<user>\w+)$',views.get_cons_doc,name='get_cons_doc'),
	url(r'^select_case/(?P<user>\w+)/(?P<case_id>\w+)$',views.select_case,name='select_case'),
	url(r'^delete_med_entry/(?P<user>\w+)$',views.delete_med_entry,name='delete_med_entry'),
	url(r'^get_cons_medicine/(?P<user>\w+)$',views.get_cons_medicine,name='get_cons_medicine'),
	url(r'^getajaxlab/(?P<user>\w+)$',views.getajaxlab,name='getajaxlab'),
	url(r'^prev_cases/(?P<user>\w+)$',views.prev_cases,name='prev_cases'),
]