# Generated by Django 3.0.3 on 2020-02-26 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pharm_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
                ('updated_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=50)),
                ('user_photo', models.ImageField(upload_to='pictures/pharm/pharm_img')),
                ('cert_image', models.ImageField(upload_to='pictures/pharm/cert_image')),
                ('User_progress', models.CharField(max_length=10, null=True)),
                ('User_otp', models.CharField(max_length=10, null=True)),
                ('User_otp_created', models.DateTimeField(null=True, verbose_name='%m/%d/%Y %H:%M:%S')),
                ('pharm_address', models.TextField()),
                ('pharm_contact_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('pharm_verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PharmLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('userip', models.CharField(max_length=50)),
                ('loginTime', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
                ('logoutTime', models.DateTimeField(blank=True, null=True, verbose_name='%m/%d/%Y %H:%M:%S')),
                ('success', models.BooleanField()),
            ],
        ),
    ]
