# Generated by Django 3.0.3 on 2020-02-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharm',
            old_name='Pharm_name',
            new_name='pharm_name',
        ),
    ]
