# Generated by Django 3.0.1 on 2020-02-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0002_auto_20200227_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharm_fb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
                ('content', models.TextField()),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
