# Generated by Django 3.0.3 on 2020-02-27 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '__first__'),
        ('pharm', '0003_pharm_fb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharm_rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.Pharm')),
                ('user_cons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User_doctor_consultancy')),
            ],
        ),
    ]
